use pellego_database;
DELETE FROM ProgressCompleted;
DELETE FROM LM_Intro;
DELETE FROM Answers;
DELETE FROM Questions;
DELETE FROM LM_Submodule;
DELETE FROM Scores;
DELETE FROM Intro_Status;
DELETE FROM Books;
DELETE FROM Library;
DELETE FROM LM_Module;
DELETE FROM User_Word_Values;
DELETE FROM Progress Completed;
DELETE FROM Users;
