use pellego_database;
DELETE FROM ProgressCompleted;
DELETE FROM LM_Intro;
DELETE FROM LM_Module;
DELETE FROM LM_Quiz;
DELETE FROM Scores;
DELETE FROM Questions;
DELETE FROM Answers;
DELETE FROM Intro_Status;
DELETE FROM Average_WPM_History;
DELETE FROM Books;
DELETE FROM User_Analytics;
DELETE FROM Library;
DELETE FROM Users;
DELETE FROM LM_Submodule;
