use pellego_database;
DELETE FROM LM_Level;
DELETE FROM LM_Module;
DELETE FROM LM_Test;
DELETE FROM Level_Status;
DELETE FROM Test_Status;
DELETE FROM User_Analytics;
DELETE FROM Library;
DELETE FROM Users;
DELETE FROM Progress;
