Use pellego_database;
   DROP TABLE User_Analytics;
   DROP TABLE Average_WPM_History;
   DROP TABLE Scores;
   DROP TABLE Answers;
   DROP TABLE Questions;
   DROP TABLE LM_Quiz;
   DROP TABLE LM_Submodule;
   DROP TABLE Intro_Status;
   DROP TABLE LM_Intro;
   DROP TABLE LM_Module;
   Drop TABLE Library;
   DROP TABLE Users;
   DROP TABLE Books;
   DROP TABLE Progress;
